# see options at https://github.com/ricardochaves/python-lint/blob/master/action.yml

name: Python Lint
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ricardochaves/python-lint@v1.4.0
      with:
        python-root-list: "grid_stability.py"
        use-flake8: true
        extra-flake8-options: --max-line-length 120
        use-black: true
        use-pycodestyle: false
        use-pylint: false
        use-mypy: false
        use-isort: false
